name: CSV Integration & Delivery
on:
  push:
    branches: [ main ]
    paths:
      - './*gradle*'
      - .github/workflows/csv-integration-delivery.yml
      - buildSrc/**/*.kt*
      - csv/**/*.kt*
  workflow_dispatch:
permissions: read-all
jobs:
  # ---------- Stage 1 ----------
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
  # ---------- Stage 2 ----------
  test:
    name: Test
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: validate-wrapper
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew csv:test --no-daemon
  # ---------- Stage 3 ----------
  deliver:
    name: Deliver to OSSRH
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deliver package to OSSRH
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew csv:publishAllPublicationToOSSRHRepository --no-daemon
