name: Gradle wrapper update
on:
  push:
    branches: [ main ]
    paths: [ .github/workflows/gradle-wrapper-upgrade.yml ]
  schedule:
    - cron: "0 12 1 * *" # At 12:00 on day-of-month 1.
jobs:
  gradle-wrapper-upgrade:
    name: Bump Gradle Wrapper
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.2
      - name: Setup Java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.20
        with:
          labels: dependencies
          reviewers: LVMVRQUXL
