name: Integration (samples)
on:
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/integration-samples.yml
      - gradle/**
      - gradle.properties
      - subprojects/samples/build.gradle.kts
      - subprojects/samples/src/**
      - build.gradle.kts
      - gradlew
      - gradlew.bat
      - settings.gradle.kts
      - yarn.lock
  push:
    branches: [ main ]
    paths:
      - .github/workflows/integration-samples.yml
      - gradle/**
      - gradle.properties
      - subprojects/samples/build.gradle.kts
      - subprojects/samples/src/**
      - build.gradle.kts
      - gradlew
      - gradlew.bat
      - settings.gradle.kts
      - yarn.lock
  workflow_dispatch:
jobs:
  ubuntu-checks:
    name: Checks on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.2
        with:
          gradle-home-cache-cleanup: true
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3.3.2
      - name: Check Gradle plugins
        run: ./gradlew :plugins:check
      - name: Test on Kotlin/JVM
        run: ./gradlew :samples:test
